name: weather_assesment 
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  animations: 2.0.7
  carousel_slider: 4.2.1
  circular_countdown_timer: 0.2.3
  cupertino_icons: 1.0.5
  dio: ^4.0.0
  dio_cache_interceptor: ^3.3.1
  equatable: 2.0.5
  firebase_analytics: 10.4.5
  firebase_core: 2.15.1
  firebase_crashlytics: 3.3.5
  firebase_messaging: 14.6.6
  flutter_dotenv: 5.1.0
  flutter_html: 3.0.0-beta.2
  flutter_local_notifications: 12.0.4
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: 2.4.9  
  flutter_screenutil: ^5.9.0
  flutter_spinkit: 5.2.0
  flutter_svg: 2.0.7
  fluttertoast: 8.2.4
  flutter_typeahead: 4.6.2
  flutter_web_browser: 0.17.1
  get_storage: 2.1.1
  get_it: 7.2.0
  go_router: 12.1.3
  html: 0.15.4
  intl: any
  image_picker: 1.0.4
  logger: 2.0.1
  lottie: 2.6.0
  package_info_plus: 4.1.0
  path_provider: 2.1.0
  path: 1.8.3
  #path: 1.9.0
  pretty_dio_logger: ^1.2.0-beta-1
  scrollable_positioned_list: 0.3.8
  share_plus: 7.1.0
  provider: ^6.1.2
  flex_color_scheme: ^7.3.1
  google_fonts: 6.1.0
  app_settings: ^5.1.1
  geolocator: ^11.0.0
  permission_handler: ^11.3.1
  geocoding: ^3.0.0
  connectivity: ^3.0.6
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  cached_network_image: ^3.3.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner:
  mockito: ^5.4.4



flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - conf/
 
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
